use std::path::Path;

pub enum CiProvider {
    GitHubActions,
    GitLabCI,
    Bitbucket,
    Jenkins,
    Unknown,
}

impl CiProvider {
    pub fn detect(repo_root: &Path) -> Self {
        if repo_root.join(".github").exists()                  { return Self::GitHubActions; }
        if repo_root.join(".gitlab-ci.yml").exists()           { return Self::GitLabCI; }
        if repo_root.join("bitbucket-pipelines.yml").exists()  { return Self::Bitbucket; }
        if repo_root.join("Jenkinsfile").exists()              { return Self::Jenkins; }
        Self::Unknown
    }

    pub fn name(&self) -> Option<&'static str> {
        match self {
            Self::GitHubActions => Some("GitHub Actions"),
            Self::GitLabCI      => Some("GitLab CI"),
            Self::Bitbucket     => Some("Bitbucket Pipelines"),
            Self::Jenkins       => Some("Jenkins"),
            Self::Unknown       => None,
        }
    }

    pub fn generate_config(&self, repo_root: &Path) -> anyhow::Result<()> {
        match self {
            Self::GitHubActions => write_github_actions(repo_root),
            Self::GitLabCI      => append_gitlab_job(repo_root),
            Self::Bitbucket     => append_bitbucket_step(repo_root),
            Self::Jenkins       => write_jenkins_file(repo_root),
            Self::Unknown       => Ok(()),
        }
    }
}

// ── GitHub Actions ────────────────────────────────────────────────────────────

const GITHUB_ACTIONS_WORKFLOW: &str = r#"name: gard

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - name: Install gard
        run: cargo install gard --quiet

      - name: Scan packages
        run: gard scan --packages --format sarif > gard.sarif

      - name: Upload to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gard.sarif
"#;

fn write_github_actions(repo_root: &Path) -> anyhow::Result<()> {
    let dir = repo_root.join(".github").join("workflows");
    std::fs::create_dir_all(&dir)?;
    let path = dir.join("gard.yml");
    if !path.exists() {
        std::fs::write(&path, GITHUB_ACTIONS_WORKFLOW)?;
    }
    Ok(())
}

// ── GitLab CI ─────────────────────────────────────────────────────────────────

const GITLAB_JOB: &str = r#"
gard-scan:
  stage: test
  image: rust:latest
  script:
    - cargo install gard --quiet
    - gard scan --packages --format sarif > gard.sarif
  artifacts:
    reports:
      sast: gard.sarif
"#;

fn append_gitlab_job(repo_root: &Path) -> anyhow::Result<()> {
    let path = repo_root.join(".gitlab-ci.yml");
    let existing = std::fs::read_to_string(&path).unwrap_or_default();
    if existing.contains("gard-scan") {
        return Ok(());
    }
    std::fs::write(&path, format!("{existing}{GITLAB_JOB}"))?;
    Ok(())
}

// ── Bitbucket Pipelines ───────────────────────────────────────────────────────

const BITBUCKET_STEP: &str = r#"
        - step:
            name: gard security scan
            script:
              - cargo install gard --quiet
              - gard scan --packages --format sarif > gard.sarif
"#;

fn append_bitbucket_step(repo_root: &Path) -> anyhow::Result<()> {
    let path = repo_root.join("bitbucket-pipelines.yml");
    let existing = std::fs::read_to_string(&path).unwrap_or_default();
    if existing.contains("gard security scan") {
        return Ok(());
    }
    std::fs::write(&path, format!("{existing}{BITBUCKET_STEP}"))?;
    Ok(())
}

// ── Jenkins ───────────────────────────────────────────────────────────────────

const JENKINS_FILE: &str = r#"// Jenkinsfile.gard — generated by `gard init`
pipeline {
    agent any
    stages {
        stage('gard security scan') {
            steps {
                sh 'cargo install gard --quiet'
                sh 'gard scan --packages --format sarif > gard.sarif'
                archiveArtifacts artifacts: 'gard.sarif'
            }
        }
    }
}
"#;

fn write_jenkins_file(repo_root: &Path) -> anyhow::Result<()> {
    let path = repo_root.join("Jenkinsfile.gard");
    if !path.exists() {
        std::fs::write(&path, JENKINS_FILE)?;
    }
    Ok(())
}
